spring:

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changeLog-master.yaml
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  application:
    name: messenger

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123ewq
  sql:
    init:
      platform: postgres


server:
  port: 8080

  error:
      include-message: ALWAYS

